name: Deploy to Docker with Docker Compose

on:
  push:
    branches:
      - vindicao-sort

jobs:
  deploy:
    runs-on: ubuntu-latest 

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r python/requirements.txt

    - name: Run Python script
      run: |
        python python/sort_products.py

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2

#     - name: Cache Docker layers
#       uses: actions/cache@v2
#       with:
#         path: /tmp/.buildx-cache
#         key: ${{ runner.os }}-buildx-${{ github.sha }}
#         restore-keys: |
#           ${{ runner.os }}-buildx-

#     - name: Set up Docker credentials
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Build and push Docker images
#       run: |
#         docker-compose -f docker-compose.yml build
        
#         docker-compose -f docker-compose.yml push

#     - name: Deploy Docker containers
#       run: |
#         docker-compose -f docker-compose.yml up -d
